import 'package:flutter/material.dart';
import 'l10n/app_localizations.dart'; // auto-generated by flutter

class AppLocalizationsHelper {
  final BuildContext context;

  AppLocalizationsHelper(this.context);

  // Shortcut to access localized strings
  AppLocalizations get _loc => AppLocalizations.of(context)!;

  // Authentication //
  String get signIn => _loc.sign_in;
  String get signUp => _loc.sign_up;
  String get email => _loc.email;
  String get password => _loc.password;

  // Errors //

  // General //
  String get appTitle => _loc.app_title;
}
