// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkInq3Wj4qJJJu1fWs-TcLJKEpsGZRK_I',
    appId: '1:616244262881:web:4e6b5d5e2d217c848004a0',
    messagingSenderId: '616244262881',
    projectId: 'personla-task',
    authDomain: 'personla-task.firebaseapp.com',
    storageBucket: 'personla-task.firebasestorage.app',
    measurementId: 'G-ZM4XRZTDWE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB80dt4Z4LDpeeXPoyRSubuBeqLyCLMssM',
    appId: '1:616244262881:android:a65fe27e7fee31738004a0',
    messagingSenderId: '616244262881',
    projectId: 'personla-task',
    storageBucket: 'personla-task.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEXDny7GzDex8qPIM1V4fHW25pi8FnIZ0',
    appId: '1:616244262881:ios:19cb057dd9612d3b8004a0',
    messagingSenderId: '616244262881',
    projectId: 'personla-task',
    storageBucket: 'personla-task.firebasestorage.app',
    iosBundleId: 'com.example.personalTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEXDny7GzDex8qPIM1V4fHW25pi8FnIZ0',
    appId: '1:616244262881:ios:19cb057dd9612d3b8004a0',
    messagingSenderId: '616244262881',
    projectId: 'personla-task',
    storageBucket: 'personla-task.firebasestorage.app',
    iosBundleId: 'com.example.personalTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkInq3Wj4qJJJu1fWs-TcLJKEpsGZRK_I',
    appId: '1:616244262881:web:1e156707c414f3128004a0',
    messagingSenderId: '616244262881',
    projectId: 'personla-task',
    authDomain: 'personla-task.firebaseapp.com',
    storageBucket: 'personla-task.firebasestorage.app',
    measurementId: 'G-CG9T526J7H',
  );
}
